TAMAYA-374 version substitution in source blocks
apache/incubator-tamaya-site pull request #4
Opened 2019-04-28 01:53 UTC by peculater

See https://github.com/asciidoctor/asciidoctor/issues/1741.

Turns out jbake was handing off the attributes to asciidoc just fine but
asciidoc doesn't interpolate those in source blocks by default. I added
the right command at the top of the blocks that contain jbake attributes, and
made some of the other blocks consistent.  Looks better in local testing
now.

2019-05-02 10:11 UTC, ottlinger requested changes
Do we need this additional property in jbake.properties?

2019-05-02 10:11 UTC, ottlinger commented on jbake.properties
> +tamaya_version_development=0.4-incubating-SNAPSHOT
Do we need this new version placeholder? Didn't find it in your changes ....

2019-05-16 07:29 UTC, peculater commented on jbake.properties
> +tamaya_version_development=0.4-incubating-SNAPSHOT
It's being used in content/documentation/quickstart.adoc but wasn't declared before.

2019-05-16 07:34 UTC, ottlinger commented on jbake.properties
> +tamaya_version_development=0.4-incubating-SNAPSHOT
@peculater thanks for spotting the mistake - we should use tamaya_version_released everywhere. To my mind it's confusing to have 2 versions in the docs.

2019-05-16 07:35 UTC, ottlinger commented on jbake.properties
> +tamaya_version_development=0.4-incubating-SNAPSHOT
A quick fgrep didn't show any further references.

2019-05-16 14:34 UTC, merged

2019-05-16 15:51 UTC, ottlinger commented
@peculater I regenerated the site, pls check :-)

Thanks for fixing this issue so far.

2019-05-17 00:31 UTC, peculater commented
Looks great, thanks for pushing it out :+1: